@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
skinparam padding 2
skinparam nodesep 50
skinparam ranksep 70
skinparam linetype ortho

' ========= Entity Definitions =========

class SightedAnimal {
  +animalName: String
  +animalId: String
  +animalGender: String {"vrouwlijk", "mannelijk", "onbekend"}
  +animalAge: String {"pasGeboren", "onvolwassen", "volwassen", "onbekend"}
  +animalCondition: String {"Gezond", "Ziek", "Dood", "Andere"}
  +intensity: String [0..1]
  +urgency: String [0..1]
}

class Interaction {
  +interactionType: String
  +userId: String
  +Report: dynamic
}

class Waarneming {
  +waarnemingId: String
  +sightedAnimals: List<SightedAnimal>
  +description: String [0..1]
  +userSelectedLocation: ReportLocation [0..1]
  +systemSelectedLocation: ReportLocation [0..1]
  +userSelectedDateTime: DateTime [0..1]
  +deviceDateTime: DateTime [0..1]
}

class Gewasschade {
  +possessionDamageReportID: String
  +possession: Possession
  +impactedAreaType: String {"Percentage", "Hectare", "Vierkante Meters"}
  +impactedArea: double
  +currentImpactDamages: String
  +estimatedTotalDamages: String
  +description: String
  +suspectedAnimal: String
  +userSelectedLocation: ReportLocation [0..1]
  +systemSelectedLocation: ReportLocation [0..1]
  +userSelectedDateTime: DateTime [0..1]
  +deviceDateTime: DateTime [0..1]
}

class Verkeersongeval {
  +accidentReportID: String
  +schade: String
  +description: String
  +sightedAnimals: List<SightedAnimal>
  +userSelectedLocation: ReportLocation [0..1]
  +systemSelectedLocation: ReportLocation [0..1]
  +userSelectedDateTime: DateTime [0..1]
  +deviceDateTime: DateTime [0..1]
}

class Possession {
  +possessionID: String
  +possessionName: String
}

class ReportLocation {
  +latitude: double
  +longitude: double
  +cityName: String
  +streetName: String
  +houseNumber: String
}

' ========= Vertical Flow =========

SightedAnimal -[hidden]down-> Interaction
Interaction -[hidden]down-> Waarneming
Waarneming -down-> Gewasschade
Gewasschade -[hidden]down- Verkeersongeval


' ========= Horizontal References =========

Gewasschade -right-> Possession
Waarneming -right-> ReportLocation 
Gewasschade -right-> ReportLocation 
Verkeersongeval -right-> ReportLocation 

Verkeersongeval -left-> SightedAnimal 
Waarneming -left-> SightedAnimal 

' ========= Optional Properties Note ========
note as OptinalNote
  **Optional Properties**
  - [0..1]: indicates that the property is optional
  - Waarneming: description, userSelectedLocation, systemSelectedLocation, dateTime
  - Gewasschade: userSelectedLocation, systemSelectedLocation, intensiteit, urgentie
  - Verkeersongeval: userSelectedLocation, systemSelectedLocation
end note



@enduml
