name: wildrapport
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  lottie: ^3.3.1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  geocoding: ^2.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  sensors_plus: ^6.1.1
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.15
  test: ^1.24.9
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.0+1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/loaders/loading_paw.json
    - assets/LogoWildlifeNL.png
    - assets/LogoHeadWildlifeNL.png
    - assets/wolf.png
    - assets/fox.png
    - assets/marten.png
    - assets/deer.png
    - assets/beer.png
    - assets/tiger.png
    - assets/gifs/login.gif
    - assets/gifs/thankyou.gif
    - assets/icons/marked_earth.png
    - assets/icons/report.png
    - assets/icons/my_report.png
    - assets/icons/rapporteren/crop_icon.png
    - assets/icons/rapporteren/health_icon.png
    - assets/icons/rapporteren/sighting_icon.png
    - assets/icons/rapporteren/accident_icon.png
    - assets/icons/category/evenhoevigen.png
    - assets/icons/category/knaagdieren.png
    - assets/icons/category/roofdieren.png
    - assets/icons/questionnaire/arrow.png
    - assets/icons/questionnaire/arrow_forward.png
    - assets/icons/questionnaire/save.png
    - assets/icons/gender/female_gender.png
    - assets/icons/gender/male_gender.png
    - assets/icons/gender/unknown_gender.png
    - assets/icons/possesion/impacted_area_type.png
    - assets/icons/possesion/gewassen/apple.svg
    - assets/icons/possesion/gewassen/corn.svg
    - assets/icons/possesion/gewassen/grass.svg
    - assets/icons/possesion/gewassen/radish_2.svg
    - assets/icons/possesion/gewassen/tomato.svg
    - assets/icons/possesion/gewassen/tulip_2.svg
    - assets/icons/possesion/gewassen/wheat.svg

    - assets/location/location_icon.png


    - .env

    

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-Regular.ttf
        - asset: assets/fonts/Arimo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Arimo-Italic.ttf
          style: italic
        - asset: assets/fonts/Arimo-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Arimo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Arimo-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Arimo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Arimo-SemiBoldItalic.ttf
          weight: 600
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
