// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCozwSuP6iiayOBjev8m_CvgSjpMZkiCK8',
    appId: '1:635742717996:web:6e12c279a3c859c5b0e989',
    messagingSenderId: '635742717996',
    projectId: 'wildrapport',
    authDomain: 'wildrapport.firebaseapp.com',
    storageBucket: 'wildrapport.firebasestorage.app',
    measurementId: 'G-32Z6EJCTM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc8cDDcQbchoiTI3SYUiRLcwVCw0yvoVc',
    appId: '1:635742717996:android:cf44a44c548e1b40b0e989',
    messagingSenderId: '635742717996',
    projectId: 'wildrapport',
    storageBucket: 'wildrapport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_F2IqAlF1FXf3fUmd-xYzJX9_5GPOO4o',
    appId: '1:635742717996:ios:da61250a0591071fb0e989',
    messagingSenderId: '635742717996',
    projectId: 'wildrapport',
    storageBucket: 'wildrapport.firebasestorage.app',
    iosBundleId: 'com.wildlife.wildrapport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_F2IqAlF1FXf3fUmd-xYzJX9_5GPOO4o',
    appId: '1:635742717996:ios:da61250a0591071fb0e989',
    messagingSenderId: '635742717996',
    projectId: 'wildrapport',
    storageBucket: 'wildrapport.firebasestorage.app',
    iosBundleId: 'com.wildlife.wildrapport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCozwSuP6iiayOBjev8m_CvgSjpMZkiCK8',
    appId: '1:635742717996:web:5a9e31b4d8bdf72cb0e989',
    messagingSenderId: '635742717996',
    projectId: 'wildrapport',
    authDomain: 'wildrapport.firebaseapp.com',
    storageBucket: 'wildrapport.firebasestorage.app',
    measurementId: 'G-NTKE2KRBVM',
  );
}
