// Mocks generated by Mockito 5.4.6 from annotations
// in wildrapport/test/business/overzicht_tests/top_container_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:wildrapport/interfaces/other/overzicht_interface.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OverzichtInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockOverzichtInterface extends _i1.Mock
    implements _i2.OverzichtInterface {
  MockOverzichtInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userName =>
      (super.noSuchMethod(
            Invocation.getter(#userName),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#userName),
            ),
          )
          as String);

  @override
  double get topContainerHeight =>
      (super.noSuchMethod(
            Invocation.getter(#topContainerHeight),
            returnValue: 0.0,
          )
          as double);

  @override
  double get welcomeFontSize =>
      (super.noSuchMethod(Invocation.getter(#welcomeFontSize), returnValue: 0.0)
          as double);

  @override
  double get usernameFontSize =>
      (super.noSuchMethod(
            Invocation.getter(#usernameFontSize),
            returnValue: 0.0,
          )
          as double);

  @override
  double get logoWidth =>
      (super.noSuchMethod(Invocation.getter(#logoWidth), returnValue: 0.0)
          as double);

  @override
  double get logoHeight =>
      (super.noSuchMethod(Invocation.getter(#logoHeight), returnValue: 0.0)
          as double);

  @override
  void updateUserName(String? newName) => super.noSuchMethod(
    Invocation.method(#updateUserName, [newName]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
